version: '3.8'

services:
  # Backend service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: vm-management-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules  # Đây là thay đổi chính: dùng anonymous volume để bảo vệ node_modules
      - ./backend/data:/app/data
    environment:
      - NODE_ENV=production
      - PORT=3001
    networks:
      - vm-network
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Cho phép container kết nối với host

  # Frontend service
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: vm-management-frontend
    restart: unless-stopped
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL=http://backend:3001/api
    depends_on:
      - backend
    networks:
      - vm-network

networks:
  vm-network:
    driver: bridge
