---
# vm_power_control.yml - Playbook để quản lý trạng thái nguồn của VM
- name: Control VM Power State
  hosts: localhost
  gather_facts: false
  vars:
    vcenter_hostname: "{{ vcenter_hostname }}"
    vcenter_username: "{{ vcenter_username }}"
    vcenter_password: "{{ vcenter_password }}"
    vcenter_validate_certs: "{{ vcenter_validate_certs }}"
    datacenter_name: "{{ datacenter_name }}"
    vm_name: "{{ vm_name }}"
    power_state: "{{ power_state }}"
  
  tasks:
    - name: Set VM power state
      community.vmware.vmware_guest_powerstate:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        validate_certs: "{{ vcenter_validate_certs }}"
        datacenter: "{{ datacenter_name }}"
        name: "{{ vm_name }}"
        state: "{{ power_state }}"
      delegate_to: localhost
      register: power_result
    
    - name: Show power state change result
      debug:
        var: power_result